version: "3.7"

services:
    service-user-app:
        container_name: user-app
        image: testing_user_app:latest
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./user-app:/home/uca_user/user-app
            - /home/uca_user/user-app/node_modules
        command: sh -c "ng serve --host 0.0.0.0"
        ports:
            - 4200:4200
